apiVersion: v1
kind: ConfigMap
metadata:
  name: peo-config
  namespace: peo-platform
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  # SQL Server Configuration
  MSSQL_PID: "Developer"
  ACCEPT_EULA: "Y"

  # Services URLs
  IDENTITY_API_URL: "http://identity-service:8080"
  GESTAO_CONTEUDO_API_URL: "http://gestao-conteudo-service:8080"
  GESTAO_ALUNOS_API_URL: "http://gestao-alunos-service:8080"
  FATURAMENTO_API_URL: "http://faturamento-service:8080"
  BFF_URL: "http://bff-service:8080"
