apiVersion: v1
kind: Service
metadata:
  name: gestao-conteudo-service
  namespace: peo-platform
spec:
  selector:
    app: gestao-conteudo-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
