apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: peo-platform
spec:
  selector:
    app: identity-api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
